version: "3"

services:
  router:
    image: dtr.andreas.dtcntr.net/docker-cemea/context-root-example:router
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: continue
      labels:
        - "com.docker.lb.hosts=demoapp.andreas.dtcntr.net"
        - "com.docker.lb.port=80"
        - "com.docker.lb.network=router"
    networks:
      - router
  nginx:
    image: nginx:alpine
    networks:
      - router
  jenkins:
    image: dtr.andreas.dtcntr.net/docker-cemea/jenkins:2.88
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - router
  web:
   image: 'gitlab/gitlab-ce:latest'
   hostname: 'demoapp.andreas.dtcntr.net'
   environment:
 #   - GITLAB_OMNIBUS_CONFIG="external_url 'http://demoapp.andreas.dtcntr.net:9090/gitlab/; gitlab_rails['gitlab_shell_ssh_port'] = 2224';"
     - GITLAB_OMNIBUS_CONFIG="external_url 'http://demoapp.andreas.dtcntr.net:9080/gitlab/'"
   ports:
     - '9080:9080'
     - '9090:443'
     - '22:22'
   volumes:
     - gitlabconfig:/etc/gitlab
     - gitlablogs:/var/log/gitlab
     - gitlabdata:/var/opt/gitlab
   networks:
      - router

volumes:
  gitlabconfig:
  gitlablogs:
  gitlabdata:  

networks:
  router:
    driver: overlay