version: "3"

services:
  router:
    image: dtr.andreas.dtcntr.net/docker-cemea/context-root-example:cicdrouter
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: continue
      labels:
        - "com.docker.lb.hosts=cicd.swarm.andreas.dtcntr.net"
        - "com.docker.lb.port=80"
        - "com.docker.lb.network=router"
    networks:
      - router
  
  jenkins:
    image: dtr.andreas.dtcntr.net/docker-cemea/jenkins:2.88
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - router

  gitlab:
   image: 'gitlab/gitlab-ce:latest'
   hostname: 'gitlab'
   environment:
     - GITLAB_OMNIBUS_CONFIG=external_url 'http://cicd.swarm.andreas.dtcntr.net/gitlab/';
   volumes:
     - gitlabconfig:/etc/gitlab
     - gitlablogs:/var/log/gitlab
     - gitlabdata:/var/opt/gitlab
   networks:
      - router
    
volumes:
  gitlabconfig:
  gitlablogs:
  gitlabdata:  

networks:
  router:
    driver: overlay